/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as example from "./example";
export type { example };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lib from "./lib";
export type { lib };
import type * as main from "./main";
export type { main };
