/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IActionHistory {
  export type ActionRecordStruct = {
    actionId: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type ActionRecordStructOutput = [BigNumber, number] & {
    actionId: BigNumber;
    status: number;
  };
}

export interface IActionHistoryInterface extends utils.Interface {
  functions: {
    "delegatedRegister(address,(uint256,uint8))": FunctionFragment;
    "register((uint256,uint8))": FunctionFragment;
    "updateHistoryStatus(uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "delegatedRegister"
      | "register"
      | "updateHistoryStatus"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "delegatedRegister",
    values: [PromiseOrValue<string>, IActionHistory.ActionRecordStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [IActionHistory.ActionRecordStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHistoryStatus",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "delegatedRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateHistoryStatus",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IActionHistory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IActionHistoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    delegatedRegister(
      addr: PromiseOrValue<string>,
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    register(
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateHistoryStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  delegatedRegister(
    addr: PromiseOrValue<string>,
    record: IActionHistory.ActionRecordStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  register(
    record: IActionHistory.ActionRecordStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateHistoryStatus(
    id: PromiseOrValue<BigNumberish>,
    status: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    delegatedRegister(
      addr: PromiseOrValue<string>,
      record: IActionHistory.ActionRecordStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    register(
      record: IActionHistory.ActionRecordStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateHistoryStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    delegatedRegister(
      addr: PromiseOrValue<string>,
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    register(
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateHistoryStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    delegatedRegister(
      addr: PromiseOrValue<string>,
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    register(
      record: IActionHistory.ActionRecordStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateHistoryStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
