/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ActionStandardRegistory {
  export type StandardStruct = {
    contractAddress: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type StandardStructOutput = [string, string, string, number] & {
    contractAddress: string;
    name: string;
    description: string;
    status: number;
  };
}

export interface ActionStandardRegistoryInterface extends utils.Interface {
  functions: {
    "actionStandardCounter()": FunctionFragment;
    "getStandardById(uint256)": FunctionFragment;
    "getStandardStatusById(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setStandard((address,string,string,uint8))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateStatus(uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "actionStandardCounter"
      | "getStandardById"
      | "getStandardStatusById"
      | "owner"
      | "renounceOwnership"
      | "setStandard"
      | "transferOwnership"
      | "updateStatus"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "actionStandardCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStandardById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStandardStatusById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setStandard",
    values: [ActionStandardRegistory.StandardStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "actionStandardCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStandardById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStandardStatusById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStandard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "SetStandard(uint256)": EventFragment;
    "UpdateStatus(uint256,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetStandard"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateStatus"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SetStandardEventObject {
  id: BigNumber;
}
export type SetStandardEvent = TypedEvent<[BigNumber], SetStandardEventObject>;

export type SetStandardEventFilter = TypedEventFilter<SetStandardEvent>;

export interface UpdateStatusEventObject {
  id: BigNumber;
  status: number;
}
export type UpdateStatusEvent = TypedEvent<
  [BigNumber, number],
  UpdateStatusEventObject
>;

export type UpdateStatusEventFilter = TypedEventFilter<UpdateStatusEvent>;

export interface ActionStandardRegistory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ActionStandardRegistoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    actionStandardCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStandardById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ActionStandardRegistory.StandardStructOutput]>;

    getStandardStatusById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStandard(
      standard: ActionStandardRegistory.StandardStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  actionStandardCounter(overrides?: CallOverrides): Promise<BigNumber>;

  getStandardById(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ActionStandardRegistory.StandardStructOutput>;

  getStandardStatusById(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStandard(
    standard: ActionStandardRegistory.StandardStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateStatus(
    id: PromiseOrValue<BigNumberish>,
    status: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    actionStandardCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getStandardById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ActionStandardRegistory.StandardStructOutput>;

    getStandardStatusById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setStandard(
      standard: ActionStandardRegistory.StandardStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "SetStandard(uint256)"(id?: null): SetStandardEventFilter;
    SetStandard(id?: null): SetStandardEventFilter;

    "UpdateStatus(uint256,uint8)"(
      id?: null,
      status?: null
    ): UpdateStatusEventFilter;
    UpdateStatus(id?: null, status?: null): UpdateStatusEventFilter;
  };

  estimateGas: {
    actionStandardCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getStandardById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStandardStatusById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStandard(
      standard: ActionStandardRegistory.StandardStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    actionStandardCounter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStandardById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStandardStatusById(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStandard(
      standard: ActionStandardRegistory.StandardStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateStatus(
      id: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
