/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IActionStandard,
  IActionStandardInterface,
} from "../../../contracts/interfaces/IActionStandard";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "supportsStandard",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IActionStandard__factory {
  static readonly abi = _abi;
  static createInterface(): IActionStandardInterface {
    return new utils.Interface(_abi) as IActionStandardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IActionStandard {
    return new Contract(address, _abi, signerOrProvider) as IActionStandard;
  }
}
