/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IActionRegistory,
  IActionRegistoryInterface,
} from "../../../contracts/interfaces/IActionRegistory";

const _abi = [
  {
    inputs: [],
    name: "actionCounter",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "actionStandardRegistory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "actionId",
        type: "uint256",
      },
    ],
    name: "allowance",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getActionById",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "standardId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "enum IActionRegistory.ActionStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct IActionRegistory.Action",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IActionRegistory__factory {
  static readonly abi = _abi;
  static createInterface(): IActionRegistoryInterface {
    return new utils.Interface(_abi) as IActionRegistoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IActionRegistory {
    return new Contract(address, _abi, signerOrProvider) as IActionRegistory;
  }
}
