/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IActionStandardRegistory,
  IActionStandardRegistoryInterface,
} from "../../../contracts/interfaces/IActionStandardRegistory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getStandardById",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "enum IActionStandardRegistory.ActionStandardStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct IActionStandardRegistory.Standard",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "standardStatus",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IActionStandardRegistory__factory {
  static readonly abi = _abi;
  static createInterface(): IActionStandardRegistoryInterface {
    return new utils.Interface(_abi) as IActionStandardRegistoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IActionStandardRegistory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IActionStandardRegistory;
  }
}
