import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Amplify, withSSRContext } from 'aws-amplify'
import awsExports from '../src/aws-exports'
import { listTodos } from '../src/graphql/queries'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
import { Todo } from '../src/API'

Amplify.configure({ ...awsExports, ssr: true })

export const getServerSideProps: GetServerSideProps = async ({ req }: GetServerSidePropsContext) => {
  const SSR = withSSRContext({ req });
  const response = await SSR.API.graphql({ query: listTodos });

  return {
    props: {
      todos: response.data.listTodos.items
    }
  };
}

type Props = {
  todos: Todo[]
}

const Home = ({ todos = []}: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>じぶんごとプラネット</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.code4japan.org">じぶんごとプラネット!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <h2>list TODOs</h2>
        {todos.map((todo)=>(<div key={todo.id}>{todo.id}:{todo.name}:{todo.description}</div>))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
